services:
  node:
    build: .
    ports:
      - "3025:3025"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
