apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
      - name: admin-panel-container
        image: my-admin-panel:latest
        ports:
        - containerPort: 3025

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-container
        image: my-front-end:latest
        ports:
        - containerPort: 8000
